### ISSUE TITLE
Use num_chains to plot the multiple chains directly?

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#140]
Going through the replication scripts here I had a quetsion:  https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/scripts/julia_replication/f124_plots.sh   is doing a number of different seeds and then we are collecting them in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/scripts/figplots/statplots_julia.jl#L7-L10   for the figures.

If we can make that change, then we can get rid of the specialized loop and just pass a number of chains in directly.

Otherwise, the code to execute multiple seeds with the scripts with an option to execute in parallel is:
```bash
#!/bin/bash

# Source the utilities script
source ./scripts/utilities.sh

# Define general variables for arguments and paths used in the run_sampler utility function
RESULTS_PATH=".replication_results"
NUM_SAMPLES="10" # "5000"
NUM_SEEDS="2" # "10"
RUN_BACKGROUND="false"  # whether to run parallel or not

# Loop through seed values and call the run_sampler function
for seed in `seq $NUM_SEEDS`; do
  if [ "$RUN_BACKGROUND" = "true" ]; then
    run_sampler $seed $NUM_SAMPLES "fit_rbc_1_kalman.jl" "${RESULTS_PATH}/f124_rbc_1_kalman_${seed}" &
  else
    run_sampler $seed $NUM_SAMPLES "fit_rbc_1_kalman.jl" "${RESULTS_PATH}/f124_rbc_1_kalman_${seed}"
  fi

done

# Wait for background processes to finish if running in the background
if [ "$RUN_BACKGROUND" = "true" ]; then
  wait
fi
```

**Comment by jlperla** [comment]
Also, if the `f124` is the figure numbers, then will rename this given the figure numbers could change.  Will call it `rbc_1_kalman_multiple_chains` etc. in case we are able to load it up, and we can rename the other chains if required.

**Comment by jlperla** [comment]
The key is to see if when we do parallel chains can we plot these separately.

**Comment by jbrightuniverse** [comment]
@jlperla We can indeed use parallel chains and StatsPlots will automatically plot each chain individually, at least for trace and density plots (I did not test others, but since it works here it is likely to work in other contexts). All that needs to be done is to execute a run with parallel chains, save the `chain.h5` file as usual, and then run just one call to `traceplot()` or `density()` on the one `.h5` file instead of the current 10 - the multiple chains will automatically populate the resulting graph without having to explicitly specify this in the plotting code.

**Comment by jlperla** [comment]
Perfect. Closing, we will use this when we finalize figures
